package uhx.sys;

/**
    ------
    DO NOT EDIT THIS FILE
    ------
    This file has be auto-generated.
    Names and codepoint values built from https://html.spec.whatwg.org/multipage/entities.json
**/

enum abstract ::typeName::(String) {

    @:to public inline function asString():String return this;

    ::foreach fields::public var ::ident:: = "::value::";
    ::end::

    public static function all():Array<::typeName::> return [
        ::foreach fields::::ident::,
        ::end::
    ];

    @:to public inline function asCodepoints():Array<Int> {
        return switch this {::foreach fields::
            case ::ident::: ::codepoints::;::end::
            case _: [];
        }
    }
}