package uhx.sys.html.std;

#if (macro || eval)
import haxe.macro.Expr;
#end

/**
    ------
    DO NOT EDIT THIS FILE
    ------
    This file has be auto-generated.
    Names and codepoint values built from https://html.spec.whatwg.org/multipage/entities.json
**/

enum abstract ::typeName::(String) {

    @:to public inline function asString():String return this;

    public static macro function has(name:ExprOf<String>):ExprOf<Bool> {
        var all = uhx.sys.::typeName::.all();
        switch name.expr {
            case EConst(CString(v)): return (all.indexOf(cast v) > -1) ? (macro true) : (macro false);
            case _:
        }
        return macro uhx.sys.::typeName::.all().indexOf(cast $name) > -1;
    }

    ::foreach fields::public var ::ident:: = "::value::";
    ::end::

    public static function all():Array<::typeName::> return [
        #if !display
        ::foreach fields::::ident::,
        ::end::
        #end
    ];

    @:to public function asCodePoints():Array<Int> {
        return switch this {
            #if !display
            ::foreach fields::
            case "::value::": ::codepoints::;::end::
            #end
            case _: [];
        }
    }

}