package uhx.sys.html.java;

import java.util.Properties;
import uhx.sys.html.java.Utils;

using StringTools;

/**
    ------
    DO NOT EDIT THIS FILE
    ------
    This file has be auto-generated.
    Names and codepoint values built from https://html.spec.whatwg.org/multipage/entities.json
**/

enum abstract ::typeName::(String) {

    @:to public inline function asString():String return this;

    public static function has(name:String):Bool {
        return HtmlEntityHelper.has(name);
    }

    ::foreach fields::public var ::ident:: = "::value::";
    ::end::

    public static function all():Array<::typeName::> {
        var values:java.util.Enumeration<String> = cast HtmlEntityHelper.properties.propertyNames();
        var results:Array<::typeName::> = [];
        while (values.hasMoreElements()) {
            var name:String = values.nextElement();
            if (!name.endsWith('_codepoints')) results.push(cast name);
        }
        return results;
    }

    @:to public function asCodePoints():Array<Int> {
        return HtmlEntityHelper.getCodePoints(this);
    }

}

class HtmlEntityHelper {

    @:isVar public static var properties(get, null):Null<Properties> = null;

    private static var resource:String = Utils.propertiesLoader();

    public static function get_properties() {
        if (properties == null) {
            properties = new Properties();
            properties.load(new java.io.StringBufferInputStream(resource));
        }
        return properties;
    }

    public static inline function has(key:String):Bool {
        return properties.getProperty(checkKey(key)) != null;
    }

    public static inline function get(key:String):String {
        return properties.getProperty(checkKey(key));
    }

    public static inline function getCodePoints(key:String):Array<Int> {
        return properties.getProperty('${checkKey(key)}_codepoints').split(',').map( s -> Std.parseInt(s) );
    }

    private static function checkKey(key:String):String {
        var start = key.indexOf('&');
        var end = key.lastIndexOf(';');
        if (start != -1) start++;
        if (end == -1) end = key.length;
        return key.substring(start, end);
    }

}